#!/bin/sh

#===========
# Autostart
#===========
$HOME/.config/bspwm/autostart.sh
bspc rule -r "*"
picom -b &
polybar -r bspwm &
polybar -r bottom &
#borders &

#===============
# Configuration
#===============
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config border_radius        8
bspc config border_width         3
bspc config window_gap           10
bspc config top_padding          30
bspc config bottom_padding       10
bspc config left_padding         3
bspc config right_padding        3

# Colors
bspc config normal_border_color		"#100d0c"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#434C5E"
bspc config presel_feedback_color	"#524957"
bspc config urgent_border_color 	"#dd2727"

#======
# Rule
#======
bspc rule -a Gpick state=floating sticky=on
bspc rule -a Pavucontrol state=floating sticky=on
bspc rule -a konsole state=floating
bspc rule -a st state=floating

bspc rule -a Emacs split_ratio=0.28 state=tiled
bspc rule -a 'Emacs:org*' state=floating
bspc rule -a 'Emacs:scratch' state=floating
