#!/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

#autostart
picom -b &

#polybar
polybar -r bspwm &
polybar -r bottom &

#borders [inner+outer]
borders &


#bspwm configuration
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config border_radius        8
bspc config border_width         10
bspc config window_gap           10
bspc config top_padding          30
bspc config bottom_padding       10
bspc config left_padding         3
bspc config right_padding        3


bspc config normal_border_color		"#05090F"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#333B33"
bspc config presel_feedback_color	"#524957"
#bspc config urgent_border_color 	"#dd2727"

#Single monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#Floating applications
bspc rule -a Gpick state=floating sticky=on
bspc rule -a Pavucontrol state=floating sticky=on
bspc rule -a konsole state=floating
bspc rule -a st state=floating


