#!/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh
#fix for moving spotify to specific workspace
#bspc config external_rules_command ~/.config/bspwm/scripts/external_rules_command

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"


#autostart
picom -b &
xrdb ~/.Xresources &
xrdb -merge ~/.Xresources &
xrdb -load ~/.Xresources &

#polybar
polybar -r bspwm &
polybar -r bottom &

2bspwm &



#BSPWM configuration
#bspc config border_radius        8
bspc config border_width         3
bspc config window_gap           10
bspc config top_padding          30
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#05090F"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#333B33"
bspc config presel_feedback_color	"#524957"
#bspc config urgent_border_color 	"#dd2727"


#Single monitor
#bspc monitor -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor  -d "☢️ " "🤬 " "⚒️ " "🍭 " "🎲 " "🎬 " "🔰 "  "🎯 " "📀 "
#bspc monitor -d "Web " "Chat " "Float " "Edit " "Tor " "Video " "Vbox " "File " "Music "
#bspc monitor -d " "  " "  " "  " "  " "  " "  " "  " "  " "  " "
bspc monitor -d "I " "II " "III " "IV " "V " "VI " "VII " "VIII " "IX " "X "
#btops &


#Floating applications
bspc rule -a Gpick state=floating sticky=on
bspc rule -a Pavucontrol state=floating sticky=on
bspc rule -a konsole state=floating
bspc rule -a st state=floating


#Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled

